export const kronosTheme = {
	ltr: "kronos-ltr",
	rtl: "kronos-rtl",
	paragraph: "kronos-paragraph",
	quote: "kronos-quote",
	heading: {
		h1: "kronos-h1",
		h2: "kronos-h2",
		h3: "kronos-h3",
		h4: "kronos-h4",
		h5: "kronos-h5",
		h6: "kronos-h6",
	},
	list: {
		nested: {
			listitem: "kronos-nested-listitem",
		},
		ol: "kronos-list-ol",
		ul: "kronos-list-ul",
		listitem: "kronos-listitem",
		listitemChecked: "kronos-listitem-checked",
		listitemUnchecked: "kronos-listitem-unchecked",
	},
	image: "kronos-image",
	link: "kronos-link",
	text: {
		bold: "kronos-text-bold",
		italic: "kronos-text-italic",
		underline: "kronos-text-underline",
		strikethrough: "kronos-text-strikethrough",
		underlineStrikethrough: "kronos-text-underline-strikethrough",
		subscript: "kronos-text-subscript",
		superscript: "kronos-text-superscript",
		code: "kronos-text-code",
	},
	code: "kronos-code",
	codeHighlight: {
		atrule: "kronos-token-attr",
		attr: "kronos-token-attr",
		boolean: "kronos-token-property",
		builtin: "kronos-token-selector",
		cdata: "kronos-token-comment",
		char: "kronos-token-selector",
		class: "kronos-token-function",
		"class-name": "kronos-token-function",
		comment: "kronos-token-comment",
		constant: "kronos-token-property",
		deleted: "kronos-token-property",
		doctype: "kronos-token-comment",
		entity: "kronos-token-operator",
		function: "kronos-token-function",
		important: "kronos-token-variable",
		inserted: "kronos-token-selector",
		keyword: "kronos-token-attr",
		namespace: "kronos-token-variable",
		number: "kronos-token-property",
		operator: "kronos-token-operator",
		prolog: "kronos-token-comment",
		property: "kronos-token-property",
		punctuation: "kronos-token-punctuation",
		regex: "kronos-token-variable",
		selector: "kronos-token-selector",
		string: "kronos-token-selector",
		symbol: "kronos-token-property",
		tag: "kronos-token-property",
		url: "kronos-token-operator",
		variable: "kronos-token-variable",
	},
	hashtag: "kronos-hashtag",
	table: "kronos-table",
	tableCell: "kronos-table-cell",
	tableCellHeader: "kronos-table-cell-header",
	tableRow: "kronos-table-row",
	tableSelected: "kronos-table-selected",
};
